export const kudaData = [
  {
    from: { name: 'Ronnie', bank: 'Kuda' },
    to: { name: 'Roscoe', bank: 'Kuda' },
    amountIn: 17,
    amountOut: 27,
    timestamp: '2023-01-25 01:26:43',
    desc: 'Industrial',
  },
  {
    from: { name: 'Buffy', bank: 'Keystone' },
    to: { name: 'Barratt', bank: 'Kuda' },
    amountIn: 19,
    amountOut: 45,
    timestamp: '2023-04-30 08:04:17',
    desc: 'Health',
  },
  {
    from: { name: 'Gabriel', bank: 'GTBank' },
    to: { name: 'Yaknov', bank: 'Fidelity' },
    amountIn: 58,
    amountOut: 34,
    timestamp: '2023-06-21 17:31:08',
    desc: 'Tools',
  },
  {
    from: { name: 'Blondell', bank: 'GTBank' },
    to: { name: 'Wisby', bank: 'GTBank' },
    amountIn: 59,
    amountOut: 36,
    timestamp: '2023-04-13 08:37:02',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Ezequiel', bank: 'Keystone' },
    to: { name: 'Hicklingbottom', bank: 'UBA' },
    amountIn: 39,
    amountOut: 26,
    timestamp: '2023-03-31 04:45:57',
    desc: 'Industrial',
  },
  {
    from: { name: 'Callean', bank: 'GTBank' },
    to: { name: 'Haskins', bank: 'Kuda' },
    amountIn: 2,
    amountOut: 51,
    timestamp: '2022-12-25 02:43:55',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Evered', bank: 'Kuda' },
    to: { name: 'Grigoriscu', bank: 'Fidelity' },
    amountIn: 58,
    amountOut: 2,
    timestamp: '2023-05-04 02:22:10',
    desc: 'Toys',
  },
  {
    from: { name: 'Clari', bank: 'Kuda' },
    to: { name: 'Pucknell', bank: 'Kuda' },
    amountIn: 28,
    amountOut: 9,
    timestamp: '2023-04-25 12:58:45',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Johann', bank: 'UBA' },
    to: { name: 'Allanson', bank: 'UBA' },
    amountIn: 52,
    amountOut: 4,
    timestamp: '2022-12-24 11:11:33',
    desc: 'Health',
  },
  {
    from: { name: 'Gwynne', bank: 'UBA' },
    to: { name: 'Barritt', bank: 'Keystone' },
    amountIn: 20,
    amountOut: 96,
    timestamp: '2023-04-17 10:11:01',
    desc: 'Games',
  },
  {
    from: { name: 'Zorine', bank: 'Keystone' },
    to: { name: 'Pow', bank: 'Keystone' },
    amountIn: 69,
    amountOut: 63,
    timestamp: '2023-04-19 23:32:42',
    desc: 'Garden',
  },
  {
    from: { name: 'Cornelia', bank: 'Kuda' },
    to: { name: 'Beste', bank: 'Kuda' },
    amountIn: 5,
    amountOut: 89,
    timestamp: '2023-01-07 08:24:47',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Ashlie', bank: 'Fidelity' },
    to: { name: 'Pearde', bank: 'GTBank' },
    amountIn: 35,
    amountOut: 1,
    timestamp: '2023-07-17 01:09:11',
    desc: 'Sports',
  },
  {
    from: { name: 'Caleb', bank: 'UBA' },
    to: { name: 'Huscroft', bank: 'UBA' },
    amountIn: 67,
    amountOut: 88,
    timestamp: '2023-04-05 06:46:29',
    desc: 'Automotive',
  },
  {
    from: { name: 'Herve', bank: 'Kuda' },
    to: { name: 'Cartner', bank: 'Kuda' },
    amountIn: 71,
    amountOut: 1,
    timestamp: '2023-07-10 10:46:30',
    desc: 'Baby',
  },
  {
    from: { name: 'Nell', bank: 'GTBank' },
    to: { name: 'Foggo', bank: 'Keystone' },
    amountIn: 28,
    amountOut: 26,
    timestamp: '2023-08-17 11:30:23',
    desc: 'Movies',
  },
  {
    from: { name: 'Brooke', bank: 'Kuda' },
    to: { name: 'Buglar', bank: 'Fidelity' },
    amountIn: 25,
    amountOut: 65,
    timestamp: '2023-09-26 12:56:38',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Janeta', bank: 'UBA' },
    to: { name: 'Boynton', bank: 'GTBank' },
    amountIn: 50,
    amountOut: 80,
    timestamp: '2022-12-09 21:55:13',
    desc: 'Tools',
  },
  {
    from: { name: 'Dennie', bank: 'Fidelity' },
    to: { name: 'Hunn', bank: 'Keystone' },
    amountIn: 58,
    amountOut: 19,
    timestamp: '2023-09-25 20:07:03',
    desc: 'Movies',
  },
  {
    from: { name: 'Sherwood', bank: 'Fidelity' },
    to: { name: 'Soots', bank: 'Keystone' },
    amountIn: 73,
    amountOut: 39,
    timestamp: '2023-02-09 17:51:23',
    desc: 'Computers',
  },
  {
    from: { name: 'Putnem', bank: 'GTBank' },
    to: { name: 'Pau', bank: 'Fidelity' },
    amountIn: 16,
    amountOut: 22,
    timestamp: '2023-05-25 12:45:22',
    desc: 'Shoes',
  },
  {
    from: { name: 'Dacy', bank: 'Fidelity' },
    to: { name: 'Sissons', bank: 'UBA' },
    amountIn: 89,
    amountOut: 51,
    timestamp: '2023-07-10 05:43:38',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Tiena', bank: 'Kuda' },
    to: { name: 'Bagge', bank: 'Fidelity' },
    amountIn: 66,
    amountOut: 16,
    timestamp: '2023-05-21 04:00:08',
    desc: 'Shoes',
  },
  {
    from: { name: 'Raimundo', bank: 'Fidelity' },
    to: { name: 'Donat', bank: 'UBA' },
    amountIn: 97,
    amountOut: 99,
    timestamp: '2022-12-06 13:55:43',
    desc: 'Home',
  },
  {
    from: { name: 'Lynsey', bank: 'Kuda' },
    to: { name: 'Weald', bank: 'GTBank' },
    amountIn: 88,
    amountOut: 85,
    timestamp: '2023-09-14 10:45:31',
    desc: 'Garden',
  },
  {
    from: { name: 'Tania', bank: 'Keystone' },
    to: { name: 'Oxburgh', bank: 'UBA' },
    amountIn: 32,
    amountOut: 43,
    timestamp: '2022-12-31 16:33:06',
    desc: 'Home',
  },
  {
    from: { name: 'Marla', bank: 'Kuda' },
    to: { name: 'Mecchi', bank: 'GTBank' },
    amountIn: 44,
    amountOut: 93,
    timestamp: '2023-01-06 05:04:39',
    desc: 'Movies',
  },
  {
    from: { name: 'Barret', bank: 'GTBank' },
    to: { name: 'Vanin', bank: 'Fidelity' },
    amountIn: 74,
    amountOut: 66,
    timestamp: '2023-01-07 10:37:04',
    desc: 'Clothing',
  },
  {
    from: { name: 'Billie', bank: 'Kuda' },
    to: { name: 'Gawthrop', bank: 'Fidelity' },
    amountIn: 77,
    amountOut: 35,
    timestamp: '2023-02-03 13:51:13',
    desc: 'Music',
  },
  {
    from: { name: 'Ermina', bank: 'Fidelity' },
    to: { name: 'Richly', bank: 'Kuda' },
    amountIn: 41,
    amountOut: 38,
    timestamp: '2023-10-12 17:19:01',
    desc: 'Computers',
  },
  {
    from: { name: 'Minnaminnie', bank: 'Fidelity' },
    to: { name: 'Rime', bank: 'GTBank' },
    amountIn: 27,
    amountOut: 45,
    timestamp: '2023-06-24 11:42:27',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Frank', bank: 'UBA' },
    to: { name: 'Toquet', bank: 'Fidelity' },
    amountIn: 49,
    amountOut: 72,
    timestamp: '2023-01-26 00:27:07',
    desc: 'Automotive',
  },
  {
    from: { name: 'Myron', bank: 'GTBank' },
    to: { name: 'Mulvey', bank: 'Keystone' },
    amountIn: 70,
    amountOut: 97,
    timestamp: '2023-04-04 16:00:09',
    desc: 'Toys',
  },
  {
    from: { name: 'Joelie', bank: 'Keystone' },
    to: { name: 'Cowling', bank: 'Kuda' },
    amountIn: 9,
    amountOut: 33,
    timestamp: '2023-11-21 06:56:57',
    desc: 'Baby',
  },
  {
    from: { name: 'Rheta', bank: 'Fidelity' },
    to: { name: 'Swedeland', bank: 'Fidelity' },
    amountIn: 37,
    amountOut: 28,
    timestamp: '2023-10-17 22:00:53',
    desc: 'Games',
  },
  {
    from: { name: 'Jacqui', bank: 'UBA' },
    to: { name: 'Husby', bank: 'GTBank' },
    amountIn: 19,
    amountOut: 58,
    timestamp: '2023-06-08 05:56:27',
    desc: 'Beauty',
  },
  {
    from: { name: 'Ruthie', bank: 'Keystone' },
    to: { name: 'Hanselmann', bank: 'UBA' },
    amountIn: 81,
    amountOut: 88,
    timestamp: '2023-05-14 08:48:16',
    desc: 'Books',
  },
  {
    from: { name: 'Riobard', bank: 'Fidelity' },
    to: { name: 'Arsmith', bank: 'Fidelity' },
    amountIn: 96,
    amountOut: 29,
    timestamp: '2023-08-14 17:15:32',
    desc: 'Health',
  },
  {
    from: { name: 'Danna', bank: 'Fidelity' },
    to: { name: 'Niesegen', bank: 'Fidelity' },
    amountIn: 87,
    amountOut: 21,
    timestamp: '2023-10-06 09:23:22',
    desc: 'Health',
  },
  {
    from: { name: 'Fanni', bank: 'UBA' },
    to: { name: 'Gemmell', bank: 'Fidelity' },
    amountIn: 95,
    amountOut: 50,
    timestamp: '2023-05-12 05:06:42',
    desc: 'Industrial',
  },
  {
    from: { name: 'Jennee', bank: 'GTBank' },
    to: { name: 'Cornilleau', bank: 'GTBank' },
    amountIn: 33,
    amountOut: 34,
    timestamp: '2022-12-10 03:09:04',
    desc: 'Music',
  },
  {
    from: { name: 'Dominik', bank: 'Fidelity' },
    to: { name: 'Brickett', bank: 'Kuda' },
    amountIn: 15,
    amountOut: 86,
    timestamp: '2023-12-04 23:17:42',
    desc: 'Home',
  },
  {
    from: { name: 'Anjanette', bank: 'UBA' },
    to: { name: 'Gilfillan', bank: 'Keystone' },
    amountIn: 58,
    amountOut: 87,
    timestamp: '2023-09-13 05:31:20',
    desc: 'Clothing',
  },
  {
    from: { name: 'Dore', bank: 'GTBank' },
    to: { name: 'Noto', bank: 'Fidelity' },
    amountIn: 32,
    amountOut: 33,
    timestamp: '2023-07-31 02:16:01',
    desc: 'Beauty',
  },
  {
    from: { name: 'Morgan', bank: 'Fidelity' },
    to: { name: 'Chmarny', bank: 'Fidelity' },
    amountIn: 82,
    amountOut: 60,
    timestamp: '2023-02-17 00:14:38',
    desc: 'Toys',
  },
  {
    from: { name: 'Karmen', bank: 'UBA' },
    to: { name: 'Tatersale', bank: 'Fidelity' },
    amountIn: 93,
    amountOut: 31,
    timestamp: '2023-09-03 01:22:34',
    desc: 'Tools',
  },
  {
    from: { name: 'Sadella', bank: 'UBA' },
    to: { name: 'Rathbone', bank: 'Keystone' },
    amountIn: 97,
    amountOut: 65,
    timestamp: '2023-11-29 22:42:02',
    desc: 'Computers',
  },
  {
    from: { name: 'Jerrie', bank: 'UBA' },
    to: { name: 'Baumaier', bank: 'GTBank' },
    amountIn: 13,
    amountOut: 20,
    timestamp: '2023-01-29 05:38:53',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Traver', bank: 'Keystone' },
    to: { name: 'Handrick', bank: 'Keystone' },
    amountIn: 96,
    amountOut: 62,
    timestamp: '2022-12-28 14:47:14',
    desc: 'Health',
  },
  {
    from: { name: 'Kerr', bank: 'Fidelity' },
    to: { name: 'Wycliff', bank: 'Kuda' },
    amountIn: 27,
    amountOut: 95,
    timestamp: '2023-04-17 22:04:56',
    desc: 'Beauty',
  },
  {
    from: { name: 'Teressa', bank: 'Kuda' },
    to: { name: 'Wands', bank: 'UBA' },
    amountIn: 20,
    amountOut: 61,
    timestamp: '2023-12-04 10:19:44',
    desc: 'Music',
  },
  {
    from: { name: 'Marlon', bank: 'Keystone' },
    to: { name: 'Ziem', bank: 'GTBank' },
    amountIn: 47,
    amountOut: 52,
    timestamp: '2023-03-27 00:34:41',
    desc: 'Toys',
  },
  {
    from: { name: 'Kayle', bank: 'Keystone' },
    to: { name: 'Olivella', bank: 'GTBank' },
    amountIn: 33,
    amountOut: 35,
    timestamp: '2023-06-04 03:11:22',
    desc: 'Music',
  },
  {
    from: { name: 'Rodrigo', bank: 'Fidelity' },
    to: { name: 'Spottiswood', bank: 'Kuda' },
    amountIn: 90,
    amountOut: 45,
    timestamp: '2023-02-18 00:36:44',
    desc: 'Movies',
  },
  {
    from: { name: 'Evelina', bank: 'GTBank' },
    to: { name: 'Choke', bank: 'Keystone' },
    amountIn: 8,
    amountOut: 2,
    timestamp: '2023-08-21 01:36:42',
    desc: 'Beauty',
  },
  {
    from: { name: 'Gusta', bank: 'Kuda' },
    to: { name: 'Van Der Weedenburg', bank: 'Fidelity' },
    amountIn: 14,
    amountOut: 89,
    timestamp: '2023-05-23 08:43:57',
    desc: 'Tools',
  },
  {
    from: { name: 'Zora', bank: 'Kuda' },
    to: { name: 'Hares', bank: 'GTBank' },
    amountIn: 46,
    amountOut: 27,
    timestamp: '2023-06-14 20:01:38',
    desc: 'Sports',
  },
  {
    from: { name: 'Sherilyn', bank: 'Fidelity' },
    to: { name: 'Coppenhall', bank: 'Kuda' },
    amountIn: 47,
    amountOut: 59,
    timestamp: '2023-07-21 01:36:31',
    desc: 'Grocery',
  },
  {
    from: { name: 'Rodney', bank: 'UBA' },
    to: { name: 'Lutman', bank: 'Fidelity' },
    amountIn: 56,
    amountOut: 61,
    timestamp: '2023-02-25 23:39:43',
    desc: 'Garden',
  },
  {
    from: { name: 'Gabbi', bank: 'GTBank' },
    to: { name: 'Lukasen', bank: 'Fidelity' },
    amountIn: 70,
    amountOut: 18,
    timestamp: '2023-07-10 19:33:54',
    desc: 'Automotive',
  },
  {
    from: { name: 'Kean', bank: 'Keystone' },
    to: { name: 'Gaskin', bank: 'Fidelity' },
    amountIn: 61,
    amountOut: 99,
    timestamp: '2022-12-27 18:04:12',
    desc: 'Toys',
  },
  {
    from: { name: 'Nikolai', bank: 'GTBank' },
    to: { name: 'Ledley', bank: 'GTBank' },
    amountIn: 32,
    amountOut: 37,
    timestamp: '2022-12-07 04:57:57',
    desc: 'Grocery',
  },
  {
    from: { name: 'Dory', bank: 'Keystone' },
    to: { name: 'Sellors', bank: 'Kuda' },
    amountIn: 33,
    amountOut: 95,
    timestamp: '2023-11-04 11:19:16',
    desc: 'Clothing',
  },
  {
    from: { name: 'Sheffield', bank: 'Kuda' },
    to: { name: 'Cawthorne', bank: 'GTBank' },
    amountIn: 83,
    amountOut: 76,
    timestamp: '2023-05-27 07:47:15',
    desc: 'Beauty',
  },
  {
    from: { name: 'Alexia', bank: 'Fidelity' },
    to: { name: 'Robotham', bank: 'Kuda' },
    amountIn: 55,
    amountOut: 75,
    timestamp: '2023-09-21 09:21:46',
    desc: 'Grocery',
  },
  {
    from: { name: 'Pauly', bank: 'Kuda' },
    to: { name: 'Boscott', bank: 'Fidelity' },
    amountIn: 78,
    amountOut: 42,
    timestamp: '2023-02-21 17:29:55',
    desc: 'Books',
  },
  {
    from: { name: 'Lowrance', bank: 'UBA' },
    to: { name: 'Hamshere', bank: 'GTBank' },
    amountIn: 63,
    amountOut: 11,
    timestamp: '2023-06-18 14:49:37',
    desc: 'Music',
  },
  {
    from: { name: 'Kaila', bank: 'Keystone' },
    to: { name: 'Beetham', bank: 'Fidelity' },
    amountIn: 15,
    amountOut: 44,
    timestamp: '2023-08-22 17:19:23',
    desc: 'Beauty',
  },
  {
    from: { name: 'Alyss', bank: 'Keystone' },
    to: { name: 'Studdard', bank: 'Fidelity' },
    amountIn: 42,
    amountOut: 30,
    timestamp: '2023-01-22 02:52:08',
    desc: 'Computers',
  },
  {
    from: { name: 'Loralie', bank: 'Kuda' },
    to: { name: 'Dayment', bank: 'GTBank' },
    amountIn: 16,
    amountOut: 88,
    timestamp: '2023-05-18 16:38:57',
    desc: 'Electronics',
  },
  {
    from: { name: 'Giraldo', bank: 'Keystone' },
    to: { name: "O'Lagene", bank: 'UBA' },
    amountIn: 82,
    amountOut: 35,
    timestamp: '2023-09-10 18:46:00',
    desc: 'Tools',
  },
  {
    from: { name: 'Loella', bank: 'Keystone' },
    to: { name: 'Sackler', bank: 'Kuda' },
    amountIn: 21,
    amountOut: 10,
    timestamp: '2023-03-17 21:21:29',
    desc: 'Sports',
  },
  {
    from: { name: 'Velvet', bank: 'Fidelity' },
    to: { name: 'Maxfield', bank: 'Kuda' },
    amountIn: 30,
    amountOut: 77,
    timestamp: '2023-02-27 00:45:29',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Ronna', bank: 'GTBank' },
    to: { name: 'Brandin', bank: 'Keystone' },
    amountIn: 14,
    amountOut: 76,
    timestamp: '2023-06-06 14:47:46',
    desc: 'Tools',
  },
  {
    from: { name: 'Antons', bank: 'Kuda' },
    to: { name: 'Bulbeck', bank: 'UBA' },
    amountIn: 97,
    amountOut: 69,
    timestamp: '2023-05-28 22:52:45',
    desc: 'Games',
  },
  {
    from: { name: 'Chloette', bank: 'Keystone' },
    to: { name: 'Edmett', bank: 'GTBank' },
    amountIn: 86,
    amountOut: 97,
    timestamp: '2023-05-14 13:05:29',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Hedvige', bank: 'Fidelity' },
    to: { name: 'Jiggens', bank: 'Kuda' },
    amountIn: 75,
    amountOut: 2,
    timestamp: '2023-09-08 11:00:58',
    desc: 'Computers',
  },
  {
    from: { name: 'Hannis', bank: 'Kuda' },
    to: { name: 'Axworthy', bank: 'Keystone' },
    amountIn: 21,
    amountOut: 68,
    timestamp: '2023-03-20 03:05:58',
    desc: 'Garden',
  },
  {
    from: { name: 'Annissa', bank: 'Kuda' },
    to: { name: 'Burridge', bank: 'Kuda' },
    amountIn: 7,
    amountOut: 68,
    timestamp: '2023-04-15 19:37:30',
    desc: 'Automotive',
  },
  {
    from: { name: 'Binny', bank: 'Fidelity' },
    to: { name: 'Winnister', bank: 'GTBank' },
    amountIn: 9,
    amountOut: 86,
    timestamp: '2023-08-24 22:35:34',
    desc: 'Movies',
  },
  {
    from: { name: 'Roger', bank: 'UBA' },
    to: { name: 'Hinrich', bank: 'GTBank' },
    amountIn: 75,
    amountOut: 96,
    timestamp: '2023-10-01 17:03:16',
    desc: 'Grocery',
  },
  {
    from: { name: 'Kit', bank: 'UBA' },
    to: { name: 'Domenico', bank: 'GTBank' },
    amountIn: 79,
    amountOut: 1,
    timestamp: '2023-10-24 17:26:43',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Trixie', bank: 'GTBank' },
    to: { name: 'Fairlem', bank: 'Keystone' },
    amountIn: 87,
    amountOut: 33,
    timestamp: '2023-08-20 23:41:17',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Rudolf', bank: 'UBA' },
    to: { name: 'Luety', bank: 'GTBank' },
    amountIn: 48,
    amountOut: 2,
    timestamp: '2023-09-19 18:36:56',
    desc: 'Sports',
  },
  {
    from: { name: 'Joan', bank: 'GTBank' },
    to: { name: 'De Benedetti', bank: 'Keystone' },
    amountIn: 78,
    amountOut: 39,
    timestamp: '2023-05-28 04:47:32',
    desc: 'Electronics',
  },
  {
    from: { name: 'Tracy', bank: 'Kuda' },
    to: { name: 'McKeighen', bank: 'Keystone' },
    amountIn: 13,
    amountOut: 38,
    timestamp: '2023-05-26 04:17:01',
    desc: 'Baby',
  },
  {
    from: { name: 'Annelise', bank: 'Kuda' },
    to: { name: 'Sherreard', bank: 'Kuda' },
    amountIn: 44,
    amountOut: 43,
    timestamp: '2023-07-29 13:04:05',
    desc: 'Books',
  },
  {
    from: { name: 'Devina', bank: 'Keystone' },
    to: { name: 'Binge', bank: 'UBA' },
    amountIn: 60,
    amountOut: 55,
    timestamp: '2023-06-10 08:19:17',
    desc: 'Health',
  },
  {
    from: { name: 'Joice', bank: 'Fidelity' },
    to: { name: 'Perrins', bank: 'Keystone' },
    amountIn: 47,
    amountOut: 71,
    timestamp: '2023-02-15 14:42:22',
    desc: 'Electronics',
  },
  {
    from: { name: 'Clayson', bank: 'Fidelity' },
    to: { name: 'Theaker', bank: 'Kuda' },
    amountIn: 90,
    amountOut: 90,
    timestamp: '2023-02-13 07:41:56',
    desc: 'Music',
  },
  {
    from: { name: 'Rica', bank: 'Keystone' },
    to: { name: 'Liles', bank: 'Keystone' },
    amountIn: 82,
    amountOut: 31,
    timestamp: '2023-11-21 04:16:11',
    desc: 'Tools',
  },
  {
    from: { name: 'Clementius', bank: 'UBA' },
    to: { name: 'Owens', bank: 'GTBank' },
    amountIn: 10,
    amountOut: 57,
    timestamp: '2023-09-11 18:16:35',
    desc: 'Baby',
  },
  {
    from: { name: 'Ninette', bank: 'GTBank' },
    to: { name: 'Fairnie', bank: 'Fidelity' },
    amountIn: 75,
    amountOut: 81,
    timestamp: '2023-04-08 21:03:58',
    desc: 'Shoes',
  },
  {
    from: { name: 'Belicia', bank: 'Kuda' },
    to: { name: 'White', bank: 'UBA' },
    amountIn: 83,
    amountOut: 94,
    timestamp: '2023-06-12 03:58:35',
    desc: 'Automotive',
  },
  {
    from: { name: 'Henrik', bank: 'Keystone' },
    to: { name: 'Harryman', bank: 'Keystone' },
    amountIn: 73,
    amountOut: 92,
    timestamp: '2023-03-27 06:08:38',
    desc: 'Health',
  },
  {
    from: { name: 'Torre', bank: 'Keystone' },
    to: { name: 'Shiril', bank: 'Keystone' },
    amountIn: 26,
    amountOut: 58,
    timestamp: '2023-09-16 16:34:49',
    desc: 'Industrial',
  },
  {
    from: { name: 'Jayne', bank: 'Fidelity' },
    to: { name: 'McPake', bank: 'Fidelity' },
    amountIn: 69,
    amountOut: 41,
    timestamp: '2022-12-13 21:55:05',
    desc: 'Books',
  },
  {
    from: { name: 'Finlay', bank: 'UBA' },
    to: { name: 'Mucillo', bank: 'GTBank' },
    amountIn: 63,
    amountOut: 3,
    timestamp: '2023-03-20 09:21:27',
    desc: 'Books',
  },
  {
    from: { name: 'Emmit', bank: 'GTBank' },
    to: { name: 'Tilbey', bank: 'Fidelity' },
    amountIn: 26,
    amountOut: 41,
    timestamp: '2023-08-02 14:53:08',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Christabella', bank: 'Fidelity' },
    to: { name: 'Silverwood', bank: 'UBA' },
    amountIn: 63,
    amountOut: 5,
    timestamp: '2023-02-09 14:26:23',
    desc: 'Health',
  },
];
