export const kudaData = [
  {
    from: { name: 'Matthus', bank: 'Asoka' },
    to: { name: 'Rannie', bank: 'Stringtough' },
    amountIn: 38,
    amountOut: 8,
    timestamp: '8/20/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Garner', bank: 'Domainer' },
    to: { name: 'Janowicz', bank: 'Gembucket' },
    amountIn: 71,
    amountOut: 65,
    timestamp: '9/8/2023',
    desc: 'Games',
  },
  {
    from: { name: 'Terry', bank: 'Konklux' },
    to: { name: 'Bresson', bank: 'Cardguard' },
    amountIn: 39,
    amountOut: 86,
    timestamp: '4/4/2023',
    desc: 'Home',
  },
  {
    from: { name: 'Damita', bank: 'Wrapsafe' },
    to: { name: 'Gero', bank: 'Greenlam' },
    amountIn: 70,
    amountOut: 15,
    timestamp: '2/5/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Lotta', bank: 'Sonsing' },
    to: { name: 'Grinyer', bank: 'Sub-Ex' },
    amountIn: 10,
    amountOut: 62,
    timestamp: '1/22/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Blakeley', bank: 'Fintone' },
    to: { name: 'Giacomuzzi', bank: 'Lotlux' },
    amountIn: 79,
    amountOut: 6,
    timestamp: '5/14/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Minnaminnie', bank: 'Zathin' },
    to: { name: 'McGrotty', bank: 'Cardify' },
    amountIn: 25,
    amountOut: 72,
    timestamp: '2/23/2023',
    desc: 'Movies',
  },
  {
    from: { name: 'Basilio', bank: 'Veribet' },
    to: { name: 'Paulet', bank: 'Tresom' },
    amountIn: 51,
    amountOut: 37,
    timestamp: '9/9/2023',
    desc: 'Automotive',
  },
  {
    from: { name: 'Jinny', bank: 'Bitchip' },
    to: { name: 'Mahady', bank: 'Y-Solowarm' },
    amountIn: 74,
    amountOut: 12,
    timestamp: '1/26/2023',
    desc: 'Movies',
  },
  {
    from: { name: 'Tabby', bank: 'Rank' },
    to: { name: 'Como', bank: 'Aerified' },
    amountIn: 53,
    amountOut: 86,
    timestamp: '6/24/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Sherm', bank: 'Y-find' },
    to: { name: 'Hirtz', bank: 'Bigtax' },
    amountIn: 1,
    amountOut: 48,
    timestamp: '8/5/2023',
    desc: 'Grocery',
  },
  {
    from: { name: 'Maible', bank: 'Asoka' },
    to: { name: 'Casone', bank: 'Voyatouch' },
    amountIn: 43,
    amountOut: 79,
    timestamp: '9/1/2023',
    desc: 'Games',
  },
  {
    from: { name: 'Bianka', bank: 'Sub-Ex' },
    to: { name: 'Spuffard', bank: 'Andalax' },
    amountIn: 50,
    amountOut: 83,
    timestamp: '3/15/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Doralyn', bank: 'Alpha' },
    to: { name: 'Scarborough', bank: 'Duobam' },
    amountIn: 7,
    amountOut: 25,
    timestamp: '12/2/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Leena', bank: 'Lotlux' },
    to: { name: 'Dimont', bank: 'Stringtough' },
    amountIn: 26,
    amountOut: 96,
    timestamp: '1/14/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Shaina', bank: 'Cardguard' },
    to: { name: 'Barrass', bank: 'Home Ing' },
    amountIn: 85,
    amountOut: 74,
    timestamp: '9/22/2023',
    desc: 'Industrial',
  },
  {
    from: { name: 'Sean', bank: 'Treeflex' },
    to: { name: 'Stichel', bank: 'Toughjoyfax' },
    amountIn: 41,
    amountOut: 77,
    timestamp: '5/20/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Casey', bank: 'Tres-Zap' },
    to: { name: 'Manuaud', bank: 'Overhold' },
    amountIn: 48,
    amountOut: 4,
    timestamp: '9/10/2023',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Raymund', bank: 'Daltfresh' },
    to: { name: 'Krienke', bank: 'It' },
    amountIn: 19,
    amountOut: 3,
    timestamp: '6/1/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Iseabal', bank: 'Latlux' },
    to: { name: 'Fearnsides', bank: 'Namfix' },
    amountIn: 4,
    amountOut: 13,
    timestamp: '4/19/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Pinchas', bank: 'Viva' },
    to: { name: 'Denman', bank: 'Stringtough' },
    amountIn: 50,
    amountOut: 95,
    timestamp: '5/14/2023',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Keelby', bank: 'Stringtough' },
    to: { name: 'Lemme', bank: 'Voyatouch' },
    amountIn: 53,
    amountOut: 60,
    timestamp: '1/13/2023',
    desc: 'Movies',
  },
  {
    from: { name: 'Gretta', bank: 'Cookley' },
    to: { name: 'Brothers', bank: 'Hatity' },
    amountIn: 60,
    amountOut: 78,
    timestamp: '12/26/2022',
    desc: 'Games',
  },
  {
    from: { name: 'Aharon', bank: 'Hatity' },
    to: { name: 'Blunsom', bank: 'Opela' },
    amountIn: 97,
    amountOut: 27,
    timestamp: '1/25/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Emlen', bank: 'Tres-Zap' },
    to: { name: 'Andreu', bank: 'Overhold' },
    amountIn: 76,
    amountOut: 21,
    timestamp: '12/27/2022',
    desc: 'Computers',
  },
  {
    from: { name: 'Grover', bank: 'Solarbreeze' },
    to: { name: 'Tethcote', bank: 'Home Ing' },
    amountIn: 67,
    amountOut: 16,
    timestamp: '6/12/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Weider', bank: 'Y-Solowarm' },
    to: { name: 'Vanyard', bank: 'Tres-Zap' },
    amountIn: 84,
    amountOut: 83,
    timestamp: '4/4/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Wood', bank: 'Holdlamis' },
    to: { name: 'Ruxton', bank: 'Daltfresh' },
    amountIn: 7,
    amountOut: 67,
    timestamp: '4/11/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Georas', bank: 'Flexidy' },
    to: { name: 'Machin', bank: 'Zamit' },
    amountIn: 73,
    amountOut: 35,
    timestamp: '1/11/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Nickey', bank: 'Ronstring' },
    to: { name: 'Sisson', bank: 'Latlux' },
    amountIn: 76,
    amountOut: 96,
    timestamp: '6/2/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Kala', bank: 'Vagram' },
    to: { name: 'McGavigan', bank: 'Fixflex' },
    amountIn: 10,
    amountOut: 73,
    timestamp: '3/25/2023',
    desc: 'Games',
  },
  {
    from: { name: 'Selia', bank: 'Ventosanzap' },
    to: { name: 'Allenson', bank: 'Fix San' },
    amountIn: 4,
    amountOut: 10,
    timestamp: '11/5/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Jonis', bank: 'Wrapsafe' },
    to: { name: 'Ardern', bank: 'Wrapsafe' },
    amountIn: 45,
    amountOut: 33,
    timestamp: '8/6/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Ettie', bank: 'Tresom' },
    to: { name: 'Champkins', bank: 'Domainer' },
    amountIn: 52,
    amountOut: 88,
    timestamp: '6/13/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Mireielle', bank: 'Hatity' },
    to: { name: 'Vakhrushev', bank: 'Transcof' },
    amountIn: 36,
    amountOut: 69,
    timestamp: '1/9/2023',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Martguerita', bank: 'Lotstring' },
    to: { name: 'Mc-Kerley', bank: 'Keylex' },
    amountIn: 69,
    amountOut: 29,
    timestamp: '12/4/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Demetri', bank: 'Tin' },
    to: { name: 'Gilliatt', bank: 'Alpha' },
    amountIn: 24,
    amountOut: 60,
    timestamp: '6/3/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Kandace', bank: 'Mat Lam Tam' },
    to: { name: 'Classen', bank: 'Lotlux' },
    amountIn: 5,
    amountOut: 100,
    timestamp: '5/14/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Pate', bank: 'Namfix' },
    to: { name: 'Libreros', bank: 'Solarbreeze' },
    amountIn: 25,
    amountOut: 77,
    timestamp: '9/4/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Corissa', bank: 'Tres-Zap' },
    to: { name: 'Haresnape', bank: 'Hatity' },
    amountIn: 80,
    amountOut: 14,
    timestamp: '6/25/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Berke', bank: 'Flexidy' },
    to: { name: 'Kenaway', bank: 'Hatity' },
    amountIn: 26,
    amountOut: 68,
    timestamp: '6/6/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Catlin', bank: 'Zaam-Dox' },
    to: { name: 'Bluett', bank: 'Span' },
    amountIn: 43,
    amountOut: 21,
    timestamp: '1/11/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Dar', bank: 'Keylex' },
    to: { name: 'Ackers', bank: 'Transcof' },
    amountIn: 64,
    amountOut: 2,
    timestamp: '12/29/2022',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Blinny', bank: 'Gembucket' },
    to: { name: 'Bothie', bank: 'Job' },
    amountIn: 46,
    amountOut: 96,
    timestamp: '7/6/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Happy', bank: 'Zoolab' },
    to: { name: 'Shivlin', bank: 'Lotstring' },
    amountIn: 13,
    amountOut: 54,
    timestamp: '10/9/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Joline', bank: 'Temp' },
    to: { name: 'Dumberell', bank: 'Sub-Ex' },
    amountIn: 20,
    amountOut: 7,
    timestamp: '2/13/2023',
    desc: 'Clothing',
  },
  {
    from: { name: 'Caren', bank: 'Aerified' },
    to: { name: 'Vevers', bank: 'Pannier' },
    amountIn: 44,
    amountOut: 26,
    timestamp: '5/1/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Sibeal', bank: 'Lotlux' },
    to: { name: 'MacDiarmond', bank: 'Lotstring' },
    amountIn: 38,
    amountOut: 92,
    timestamp: '4/27/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Thelma', bank: 'Cardify' },
    to: { name: 'Hylands', bank: 'It' },
    amountIn: 38,
    amountOut: 36,
    timestamp: '12/14/2022',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Nolie', bank: 'Ventosanzap' },
    to: { name: 'Reinert', bank: 'Aerified' },
    amountIn: 16,
    amountOut: 93,
    timestamp: '5/15/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Johnette', bank: 'Duobam' },
    to: { name: 'Melrose', bank: 'Tres-Zap' },
    amountIn: 74,
    amountOut: 22,
    timestamp: '9/5/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Vickie', bank: 'Tin' },
    to: { name: 'Lanigan', bank: 'Latlux' },
    amountIn: 17,
    amountOut: 27,
    timestamp: '4/25/2023',
    desc: 'Industrial',
  },
  {
    from: { name: 'Wayne', bank: 'Tampflex' },
    to: { name: 'Salzburger', bank: 'Lotstring' },
    amountIn: 18,
    amountOut: 3,
    timestamp: '10/13/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Ursola', bank: 'Holdlamis' },
    to: { name: 'Ainley', bank: 'Keylex' },
    amountIn: 4,
    amountOut: 54,
    timestamp: '10/19/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Elise', bank: 'Zathin' },
    to: { name: 'Delacroix', bank: 'Domainer' },
    amountIn: 68,
    amountOut: 61,
    timestamp: '5/6/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Meara', bank: 'Alpha' },
    to: { name: 'Sennett', bank: 'Tempsoft' },
    amountIn: 17,
    amountOut: 61,
    timestamp: '5/13/2023',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Liana', bank: 'Stim' },
    to: { name: 'Cancellario', bank: 'Bigtax' },
    amountIn: 7,
    amountOut: 98,
    timestamp: '12/29/2022',
    desc: 'Toys',
  },
  {
    from: { name: 'Melly', bank: 'Zaam-Dox' },
    to: { name: 'Pieroni', bank: 'Cardify' },
    amountIn: 29,
    amountOut: 71,
    timestamp: '2/22/2023',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Cly', bank: 'Pannier' },
    to: { name: 'Chadwyck', bank: 'Otcom' },
    amountIn: 75,
    amountOut: 11,
    timestamp: '5/25/2023',
    desc: 'Games',
  },
  {
    from: { name: 'Magdaia', bank: 'Voltsillam' },
    to: { name: 'Heiton', bank: 'Konklux' },
    amountIn: 12,
    amountOut: 62,
    timestamp: '12/7/2022',
    desc: 'Beauty',
  },
  {
    from: { name: 'Audrey', bank: 'Cardify' },
    to: { name: 'Backs', bank: 'Redhold' },
    amountIn: 97,
    amountOut: 27,
    timestamp: '8/27/2023',
    desc: 'Automotive',
  },
  {
    from: { name: 'Giacopo', bank: 'Span' },
    to: { name: 'Alyokhin', bank: 'Aerified' },
    amountIn: 30,
    amountOut: 14,
    timestamp: '11/16/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Lise', bank: 'Bigtax' },
    to: { name: 'Casari', bank: 'Gembucket' },
    amountIn: 5,
    amountOut: 33,
    timestamp: '8/28/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Zulema', bank: 'Prodder' },
    to: { name: 'Twaits', bank: 'Aerified' },
    amountIn: 95,
    amountOut: 53,
    timestamp: '11/22/2023',
    desc: 'Home',
  },
  {
    from: { name: 'Row', bank: 'Latlux' },
    to: { name: 'Sandom', bank: 'Flexidy' },
    amountIn: 9,
    amountOut: 35,
    timestamp: '12/17/2022',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Drew', bank: 'Vagram' },
    to: { name: 'Kloss', bank: 'Greenlam' },
    amountIn: 36,
    amountOut: 70,
    timestamp: '12/11/2022',
    desc: 'Electronics',
  },
  {
    from: { name: 'Mycah', bank: 'Viva' },
    to: { name: 'Kitteridge', bank: 'Sub-Ex' },
    amountIn: 75,
    amountOut: 73,
    timestamp: '12/6/2022',
    desc: 'Kids',
  },
  {
    from: { name: 'Basia', bank: 'Voltsillam' },
    to: { name: 'Bridell', bank: 'Vagram' },
    amountIn: 92,
    amountOut: 56,
    timestamp: '4/29/2023',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Federica', bank: 'Fix San' },
    to: { name: 'Huckle', bank: 'Bitchip' },
    amountIn: 60,
    amountOut: 92,
    timestamp: '4/8/2023',
    desc: 'Games',
  },
  {
    from: { name: 'Moyra', bank: 'Kanlam' },
    to: { name: 'Fawks', bank: 'Ronstring' },
    amountIn: 64,
    amountOut: 48,
    timestamp: '6/9/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Rudie', bank: 'Alphazap' },
    to: { name: 'Fishwick', bank: 'Overhold' },
    amountIn: 19,
    amountOut: 17,
    timestamp: '8/2/2023',
    desc: 'Games',
  },
  {
    from: { name: 'Jozef', bank: 'Redhold' },
    to: { name: 'Lodwig', bank: 'Transcof' },
    amountIn: 73,
    amountOut: 61,
    timestamp: '9/13/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Corissa', bank: 'Tempsoft' },
    to: { name: 'Gregorin', bank: 'Sub-Ex' },
    amountIn: 92,
    amountOut: 23,
    timestamp: '9/16/2023',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Jeanne', bank: 'Hatity' },
    to: { name: 'Reucastle', bank: 'Fixflex' },
    amountIn: 56,
    amountOut: 44,
    timestamp: '8/12/2023',
    desc: 'Automotive',
  },
  {
    from: { name: 'Querida', bank: 'Zoolab' },
    to: { name: 'Daburn', bank: 'Zaam-Dox' },
    amountIn: 75,
    amountOut: 70,
    timestamp: '2/24/2023',
    desc: 'Clothing',
  },
  {
    from: { name: 'Hamish', bank: 'Stronghold' },
    to: { name: 'McDonagh', bank: 'Home Ing' },
    amountIn: 43,
    amountOut: 10,
    timestamp: '7/3/2023',
    desc: 'Automotive',
  },
  {
    from: { name: 'Neysa', bank: 'Overhold' },
    to: { name: 'Lyles', bank: 'Stim' },
    amountIn: 92,
    amountOut: 92,
    timestamp: '12/7/2022',
    desc: 'Tools',
  },
  {
    from: { name: 'Matt', bank: 'Trippledex' },
    to: { name: 'Kantor', bank: 'Subin' },
    amountIn: 26,
    amountOut: 16,
    timestamp: '12/28/2022',
    desc: 'Health',
  },
  {
    from: { name: 'Helsa', bank: 'Cardify' },
    to: { name: 'Lukovic', bank: 'Regrant' },
    amountIn: 18,
    amountOut: 62,
    timestamp: '11/18/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Barb', bank: 'Flexidy' },
    to: { name: 'Wolfendell', bank: 'Quo Lux' },
    amountIn: 32,
    amountOut: 2,
    timestamp: '3/22/2023',
    desc: 'Movies',
  },
  {
    from: { name: 'Fayina', bank: 'Aerified' },
    to: { name: 'Kegan', bank: 'Kanlam' },
    amountIn: 4,
    amountOut: 20,
    timestamp: '10/17/2023',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Denni', bank: 'Greenlam' },
    to: { name: 'Bottleson', bank: 'Alpha' },
    amountIn: 88,
    amountOut: 61,
    timestamp: '11/17/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Jana', bank: 'Flowdesk' },
    to: { name: 'Paoletto', bank: 'Bigtax' },
    amountIn: 46,
    amountOut: 75,
    timestamp: '8/16/2023',
    desc: 'Automotive',
  },
  {
    from: { name: 'Debera', bank: 'Vagram' },
    to: { name: 'Hunting', bank: 'Bitwolf' },
    amountIn: 98,
    amountOut: 70,
    timestamp: '3/17/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Helge', bank: 'Home Ing' },
    to: { name: 'Pitkeathly', bank: 'Hatity' },
    amountIn: 96,
    amountOut: 82,
    timestamp: '4/21/2023',
    desc: 'Clothing',
  },
  {
    from: { name: 'Jackie', bank: 'Konklab' },
    to: { name: 'Lundie', bank: 'Fixflex' },
    amountIn: 23,
    amountOut: 19,
    timestamp: '3/20/2023',
    desc: 'Automotive',
  },
  {
    from: { name: 'Aigneis', bank: 'Greenlam' },
    to: { name: 'Goodredge', bank: 'Voltsillam' },
    amountIn: 39,
    amountOut: 74,
    timestamp: '7/6/2023',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Dory', bank: 'Stringtough' },
    to: { name: 'Narup', bank: 'Tin' },
    amountIn: 90,
    amountOut: 65,
    timestamp: '3/24/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Dion', bank: 'Redhold' },
    to: { name: 'Olley', bank: 'Opela' },
    amountIn: 82,
    amountOut: 4,
    timestamp: '4/16/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Milli', bank: 'Bytecard' },
    to: { name: 'Slany', bank: 'Wrapsafe' },
    amountIn: 1,
    amountOut: 73,
    timestamp: '8/20/2023',
    desc: 'Shoes',
  },
  {
    from: { name: 'Ingamar', bank: 'Transcof' },
    to: { name: 'Stepto', bank: 'Flexidy' },
    amountIn: 49,
    amountOut: 82,
    timestamp: '7/2/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Eulalie', bank: 'Stronghold' },
    to: { name: 'Ellit', bank: 'Opela' },
    amountIn: 81,
    amountOut: 30,
    timestamp: '2/6/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Sophi', bank: 'Flexidy' },
    to: { name: 'Curtain', bank: 'Flexidy' },
    amountIn: 96,
    amountOut: 71,
    timestamp: '1/31/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Allissa', bank: 'Temp' },
    to: { name: 'Frise', bank: 'Gembucket' },
    amountIn: 47,
    amountOut: 2,
    timestamp: '10/11/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Jamaal', bank: 'Vagram' },
    to: { name: 'Tindle', bank: 'Overhold' },
    amountIn: 45,
    amountOut: 18,
    timestamp: '4/16/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Corrie', bank: 'Quo Lux' },
    to: { name: 'Huband', bank: 'Asoka' },
    amountIn: 21,
    amountOut: 33,
    timestamp: '8/26/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Web', bank: 'Y-find' },
    to: { name: 'Blackwell', bank: 'Tin' },
    amountIn: 95,
    amountOut: 92,
    timestamp: '7/24/2023',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Pennie', bank: 'Home Ing' },
    to: { name: 'Prozescky', bank: 'Sonsing' },
    amountIn: 76,
    amountOut: 25,
    timestamp: '12/8/2022',
    desc: 'Garden',
  },
  {
    from: { name: 'Chandler', bank: 'Asoka' },
    to: { name: 'Cantopher', bank: 'Opela' },
    amountIn: 37,
    amountOut: 41,
    timestamp: '10/19/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Calli', bank: 'Voltsillam' },
    to: { name: 'Brecken', bank: 'Fintone' },
    amountIn: 14,
    amountOut: 76,
    timestamp: '10/16/2023',
    desc: 'Health',
  },
];
