export const ubaData = [
  {
    from: { name: 'Duky', bank: 'Keylex' },
    to: { name: 'Flaune', bank: 'Fixflex' },
    amountIn: 54,
    amountOut: 40,
    timestamp: '3/26/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Guthry', bank: 'Flowdesk' },
    to: { name: 'Skillicorn', bank: 'Zoolab' },
    amountIn: 28,
    amountOut: 68,
    timestamp: '10/7/2023',
    desc: 'Shoes',
  },
  {
    from: { name: 'Che', bank: 'Job' },
    to: { name: 'Eisig', bank: 'Greenlam' },
    amountIn: 93,
    amountOut: 3,
    timestamp: '8/1/2023',
    desc: 'Shoes',
  },
  {
    from: { name: 'Kettie', bank: 'Daltfresh' },
    to: { name: 'Pedroli', bank: 'Hatity' },
    amountIn: 46,
    amountOut: 9,
    timestamp: '4/6/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Alexi', bank: 'It' },
    to: { name: 'Gamett', bank: 'Home Ing' },
    amountIn: 47,
    amountOut: 26,
    timestamp: '9/25/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Kathrine', bank: 'Latlux' },
    to: { name: 'McVeagh', bank: 'Wrapsafe' },
    amountIn: 91,
    amountOut: 94,
    timestamp: '10/1/2023',
    desc: 'Beauty',
  },
  {
    from: { name: 'Wallis', bank: 'Opela' },
    to: { name: 'Arnaldi', bank: 'Viva' },
    amountIn: 27,
    amountOut: 72,
    timestamp: '7/13/2023',
    desc: 'Clothing',
  },
  {
    from: { name: 'Windham', bank: 'Domainer' },
    to: { name: 'Alden', bank: 'Konklux' },
    amountIn: 81,
    amountOut: 98,
    timestamp: '1/29/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Nap', bank: 'Home Ing' },
    to: { name: 'Wickerson', bank: 'Bitchip' },
    amountIn: 81,
    amountOut: 41,
    timestamp: '11/12/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Charline', bank: 'Bamity' },
    to: { name: 'Gislebert', bank: 'Stim' },
    amountIn: 66,
    amountOut: 92,
    timestamp: '10/24/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Kelly', bank: 'Andalax' },
    to: { name: 'Bruntjen', bank: 'Konklux' },
    amountIn: 53,
    amountOut: 75,
    timestamp: '7/1/2023',
    desc: 'Beauty',
  },
  {
    from: { name: 'Wilburt', bank: 'Greenlam' },
    to: { name: 'Rasher', bank: 'Fixflex' },
    amountIn: 28,
    amountOut: 61,
    timestamp: '3/21/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Ardisj', bank: 'Namfix' },
    to: { name: 'Iddison', bank: 'Lotlux' },
    amountIn: 13,
    amountOut: 7,
    timestamp: '7/10/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Dallon', bank: 'Latlux' },
    to: { name: 'Lochrie', bank: 'Stronghold' },
    amountIn: 74,
    amountOut: 40,
    timestamp: '7/11/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Chrysler', bank: 'Andalax' },
    to: { name: 'Francke', bank: 'Home Ing' },
    amountIn: 62,
    amountOut: 65,
    timestamp: '8/21/2023',
    desc: 'Clothing',
  },
  {
    from: { name: 'Fan', bank: 'Treeflex' },
    to: { name: 'Cobleigh', bank: 'Flexidy' },
    amountIn: 47,
    amountOut: 20,
    timestamp: '9/2/2023',
    desc: 'Home',
  },
  {
    from: { name: 'Glenine', bank: 'Voyatouch' },
    to: { name: 'Pawelke', bank: 'Bitchip' },
    amountIn: 80,
    amountOut: 65,
    timestamp: '4/1/2023',
    desc: 'Home',
  },
  {
    from: { name: 'Binny', bank: 'Span' },
    to: { name: 'Vasyanin', bank: 'Daltfresh' },
    amountIn: 42,
    amountOut: 88,
    timestamp: '10/12/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Pia', bank: 'Bitchip' },
    to: { name: 'McCrudden', bank: 'Sonair' },
    amountIn: 79,
    amountOut: 63,
    timestamp: '2/12/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Reube', bank: 'Sonsing' },
    to: { name: 'Brigge', bank: 'Biodex' },
    amountIn: 79,
    amountOut: 29,
    timestamp: '4/22/2023',
    desc: 'Beauty',
  },
  {
    from: { name: 'Sybille', bank: 'Greenlam' },
    to: { name: 'Silk', bank: 'Sub-Ex' },
    amountIn: 43,
    amountOut: 34,
    timestamp: '12/20/2022',
    desc: 'Music',
  },
  {
    from: { name: 'Uriah', bank: 'Tresom' },
    to: { name: 'Weiss', bank: 'Span' },
    amountIn: 49,
    amountOut: 96,
    timestamp: '10/7/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Lon', bank: 'Voltsillam' },
    to: { name: 'Stonhewer', bank: 'Y-Solowarm' },
    amountIn: 53,
    amountOut: 73,
    timestamp: '7/26/2023',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Chiquita', bank: 'Y-Solowarm' },
    to: { name: 'Cotty', bank: 'Konklab' },
    amountIn: 7,
    amountOut: 74,
    timestamp: '3/3/2023',
    desc: 'Home',
  },
  {
    from: { name: 'Giffie', bank: 'Aerified' },
    to: { name: 'Perrycost', bank: 'Toughjoyfax' },
    amountIn: 35,
    amountOut: 64,
    timestamp: '9/26/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Deane', bank: 'Fix San' },
    to: { name: 'Tubbs', bank: 'Toughjoyfax' },
    amountIn: 39,
    amountOut: 63,
    timestamp: '4/15/2023',
    desc: 'Home',
  },
  {
    from: { name: 'Luce', bank: 'Alphazap' },
    to: { name: 'Dalliston', bank: 'Temp' },
    amountIn: 44,
    amountOut: 10,
    timestamp: '10/30/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Brady', bank: 'Transcof' },
    to: { name: 'Penni', bank: 'Home Ing' },
    amountIn: 96,
    amountOut: 24,
    timestamp: '8/31/2023',
    desc: 'Tools',
  },
  {
    from: { name: 'Stevie', bank: 'Zathin' },
    to: { name: 'Renn', bank: 'Job' },
    amountIn: 77,
    amountOut: 79,
    timestamp: '4/30/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Polly', bank: 'Sub-Ex' },
    to: { name: 'Chessum', bank: 'Keylex' },
    amountIn: 5,
    amountOut: 91,
    timestamp: '10/28/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Sheff', bank: 'Vagram' },
    to: { name: 'MacLennan', bank: 'Zamit' },
    amountIn: 32,
    amountOut: 27,
    timestamp: '10/25/2023',
    desc: 'Industrial',
  },
  {
    from: { name: 'Natividad', bank: 'Andalax' },
    to: { name: 'Mc Meekin', bank: 'Sonair' },
    amountIn: 54,
    amountOut: 39,
    timestamp: '3/5/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Iggie', bank: 'Prodder' },
    to: { name: 'Alessandrelli', bank: 'Cookley' },
    amountIn: 73,
    amountOut: 24,
    timestamp: '4/26/2023',
    desc: 'Movies',
  },
  {
    from: { name: 'Margareta', bank: 'Keylex' },
    to: { name: 'Cranidge', bank: 'Keylex' },
    amountIn: 17,
    amountOut: 23,
    timestamp: '7/19/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Ephrem', bank: 'Mat Lam Tam' },
    to: { name: 'Pixton', bank: 'Zamit' },
    amountIn: 64,
    amountOut: 34,
    timestamp: '6/23/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Giulia', bank: 'Stringtough' },
    to: { name: 'Moulin', bank: 'Namfix' },
    amountIn: 64,
    amountOut: 56,
    timestamp: '1/29/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Ray', bank: 'It' },
    to: { name: 'Snodin', bank: 'Flexidy' },
    amountIn: 15,
    amountOut: 55,
    timestamp: '11/16/2023',
    desc: 'Grocery',
  },
  {
    from: { name: 'Nelson', bank: 'Vagram' },
    to: { name: 'Korb', bank: 'Kanlam' },
    amountIn: 88,
    amountOut: 27,
    timestamp: '8/21/2023',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Crysta', bank: 'Lotlux' },
    to: { name: 'Prator', bank: 'Temp' },
    amountIn: 75,
    amountOut: 66,
    timestamp: '12/7/2022',
    desc: 'Automotive',
  },
  {
    from: { name: 'Coop', bank: 'Subin' },
    to: { name: 'Bowell', bank: 'Y-Solowarm' },
    amountIn: 38,
    amountOut: 11,
    timestamp: '1/19/2023',
    desc: 'Outdoors',
  },
  {
    from: { name: 'Roz', bank: 'Job' },
    to: { name: 'Bennison', bank: 'Redhold' },
    amountIn: 51,
    amountOut: 58,
    timestamp: '6/18/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Trevar', bank: 'Namfix' },
    to: { name: 'Bencher', bank: 'Lotlux' },
    amountIn: 38,
    amountOut: 92,
    timestamp: '4/10/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Orella', bank: 'Greenlam' },
    to: { name: 'Brendeke', bank: 'Gembucket' },
    amountIn: 64,
    amountOut: 49,
    timestamp: '11/3/2023',
    desc: 'Beauty',
  },
  {
    from: { name: 'Craggie', bank: 'Regrant' },
    to: { name: 'French', bank: 'Hatity' },
    amountIn: 66,
    amountOut: 95,
    timestamp: '11/26/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Deborah', bank: 'Tin' },
    to: { name: 'Nozzolii', bank: 'Lotstring' },
    amountIn: 46,
    amountOut: 27,
    timestamp: '12/24/2022',
    desc: 'Industrial',
  },
  {
    from: { name: 'Esra', bank: 'Vagram' },
    to: { name: 'De Avenell', bank: 'Zoolab' },
    amountIn: 10,
    amountOut: 90,
    timestamp: '5/7/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Hamel', bank: 'Bytecard' },
    to: { name: 'Hallatt', bank: 'Fixflex' },
    amountIn: 73,
    amountOut: 21,
    timestamp: '3/2/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Clark', bank: 'Holdlamis' },
    to: { name: 'Bernini', bank: 'Biodex' },
    amountIn: 39,
    amountOut: 23,
    timestamp: '1/24/2023',
    desc: 'Clothing',
  },
  {
    from: { name: 'Kaylyn', bank: 'Zontrax' },
    to: { name: 'Evens', bank: 'Fintone' },
    amountIn: 82,
    amountOut: 39,
    timestamp: '7/15/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Sidoney', bank: 'Vagram' },
    to: { name: 'Zanicchi', bank: 'Trippledex' },
    amountIn: 17,
    amountOut: 30,
    timestamp: '8/8/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Lorraine', bank: 'Daltfresh' },
    to: { name: 'McKay', bank: 'Subin' },
    amountIn: 46,
    amountOut: 45,
    timestamp: '1/1/2023',
    desc: 'Grocery',
  },
  {
    from: { name: 'Bili', bank: 'Konklux' },
    to: { name: 'Sainte Paul', bank: 'Bigtax' },
    amountIn: 10,
    amountOut: 54,
    timestamp: '1/31/2023',
    desc: 'Industrial',
  },
  {
    from: { name: 'Ezmeralda', bank: 'Tin' },
    to: { name: 'Prayer', bank: 'Lotstring' },
    amountIn: 60,
    amountOut: 95,
    timestamp: '2/4/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Naoma', bank: 'Trippledex' },
    to: { name: 'Gare', bank: 'Biodex' },
    amountIn: 98,
    amountOut: 72,
    timestamp: '9/26/2023',
    desc: 'Books',
  },
  {
    from: { name: 'Annie', bank: 'Fintone' },
    to: { name: 'Brackstone', bank: 'Cookley' },
    amountIn: 94,
    amountOut: 25,
    timestamp: '5/21/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Sascha', bank: 'Alphazap' },
    to: { name: 'Buzin', bank: 'Mat Lam Tam' },
    amountIn: 47,
    amountOut: 8,
    timestamp: '6/25/2023',
    desc: 'Movies',
  },
  {
    from: { name: 'Winny', bank: 'Fintone' },
    to: { name: 'Boakes', bank: 'Fixflex' },
    amountIn: 24,
    amountOut: 77,
    timestamp: '3/26/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Ardenia', bank: 'Zontrax' },
    to: { name: 'Usborn', bank: 'Greenlam' },
    amountIn: 90,
    amountOut: 33,
    timestamp: '12/11/2022',
    desc: 'Kids',
  },
  {
    from: { name: 'Charla', bank: 'Konklux' },
    to: { name: 'Hadny', bank: 'Lotstring' },
    amountIn: 95,
    amountOut: 74,
    timestamp: '4/17/2023',
    desc: 'Movies',
  },
  {
    from: { name: 'Bevon', bank: 'Stim' },
    to: { name: 'Valencia', bank: 'Sonsing' },
    amountIn: 47,
    amountOut: 45,
    timestamp: '1/19/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Stacy', bank: 'Domainer' },
    to: { name: 'Johannes', bank: 'Veribet' },
    amountIn: 57,
    amountOut: 25,
    timestamp: '4/24/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Ferrell', bank: 'Fixflex' },
    to: { name: 'Espinet', bank: 'Pannier' },
    amountIn: 6,
    amountOut: 97,
    timestamp: '4/29/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Anastassia', bank: 'Stim' },
    to: { name: 'Ilive', bank: 'Veribet' },
    amountIn: 29,
    amountOut: 22,
    timestamp: '10/28/2023',
    desc: 'Shoes',
  },
  {
    from: { name: 'Nyssa', bank: 'Bitchip' },
    to: { name: 'Pegden', bank: 'Quo Lux' },
    amountIn: 92,
    amountOut: 63,
    timestamp: '6/27/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Osmond', bank: 'Toughjoyfax' },
    to: { name: 'Francescuzzi', bank: 'Kanlam' },
    amountIn: 9,
    amountOut: 5,
    timestamp: '10/9/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Gray', bank: 'Viva' },
    to: { name: 'Mularkey', bank: 'Regrant' },
    amountIn: 98,
    amountOut: 59,
    timestamp: '6/25/2023',
    desc: 'Beauty',
  },
  {
    from: { name: 'Fidelio', bank: 'Fintone' },
    to: { name: 'Sells', bank: 'Kanlam' },
    amountIn: 77,
    amountOut: 30,
    timestamp: '8/20/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Heddie', bank: 'Sub-Ex' },
    to: { name: 'Owen', bank: 'Hatity' },
    amountIn: 41,
    amountOut: 26,
    timestamp: '5/8/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Maggi', bank: 'Bigtax' },
    to: { name: 'Leuren', bank: 'Bitchip' },
    amountIn: 92,
    amountOut: 18,
    timestamp: '1/3/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Randall', bank: 'Bigtax' },
    to: { name: 'Marzelo', bank: 'It' },
    amountIn: 68,
    amountOut: 29,
    timestamp: '8/1/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Freddi', bank: 'Regrant' },
    to: { name: 'Groveham', bank: 'Ventosanzap' },
    amountIn: 45,
    amountOut: 70,
    timestamp: '7/11/2023',
    desc: 'Health',
  },
  {
    from: { name: 'Newton', bank: 'Kanlam' },
    to: { name: 'Wardel', bank: 'Y-find' },
    amountIn: 85,
    amountOut: 26,
    timestamp: '10/23/2023',
    desc: 'Kids',
  },
  {
    from: { name: 'Nevil', bank: 'Andalax' },
    to: { name: 'Mahood', bank: 'Namfix' },
    amountIn: 39,
    amountOut: 65,
    timestamp: '10/15/2023',
    desc: 'Grocery',
  },
  {
    from: { name: 'Irita', bank: 'Zontrax' },
    to: { name: 'Semour', bank: 'Tresom' },
    amountIn: 81,
    amountOut: 98,
    timestamp: '7/5/2023',
    desc: 'Music',
  },
  {
    from: { name: 'Loreen', bank: 'Fixflex' },
    to: { name: 'Ende', bank: 'Tempsoft' },
    amountIn: 91,
    amountOut: 56,
    timestamp: '12/11/2022',
    desc: 'Books',
  },
  {
    from: { name: 'Kandy', bank: 'Temp' },
    to: { name: 'Arthy', bank: 'Domainer' },
    amountIn: 31,
    amountOut: 86,
    timestamp: '2/19/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Ario', bank: 'Stim' },
    to: { name: 'Bane', bank: 'Tres-Zap' },
    amountIn: 29,
    amountOut: 44,
    timestamp: '9/30/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Armstrong', bank: 'Transcof' },
    to: { name: 'Cuningham', bank: 'Asoka' },
    amountIn: 6,
    amountOut: 60,
    timestamp: '3/30/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Briggs', bank: 'Stringtough' },
    to: { name: 'Forman', bank: 'Treeflex' },
    amountIn: 27,
    amountOut: 19,
    timestamp: '8/23/2023',
    desc: 'Toys',
  },
  {
    from: { name: 'Meir', bank: 'Vagram' },
    to: { name: 'Chennells', bank: 'Sonsing' },
    amountIn: 79,
    amountOut: 25,
    timestamp: '11/7/2023',
    desc: 'Industrial',
  },
  {
    from: { name: 'Leonard', bank: 'Tresom' },
    to: { name: 'Borgnol', bank: 'Domainer' },
    amountIn: 76,
    amountOut: 94,
    timestamp: '9/7/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Levon', bank: 'Asoka' },
    to: { name: 'Gulston', bank: 'It' },
    amountIn: 77,
    amountOut: 76,
    timestamp: '11/24/2023',
    desc: 'Home',
  },
  {
    from: { name: 'Gino', bank: 'Ventosanzap' },
    to: { name: 'Yve', bank: 'Sonsing' },
    amountIn: 71,
    amountOut: 9,
    timestamp: '8/25/2023',
    desc: 'Tools',
  },
  {
    from: { name: 'Chad', bank: 'Domainer' },
    to: { name: 'Burmaster', bank: 'Opela' },
    amountIn: 96,
    amountOut: 29,
    timestamp: '7/6/2023',
    desc: 'Industrial',
  },
  {
    from: { name: 'Sarina', bank: 'Bigtax' },
    to: { name: 'McCarlich', bank: 'Viva' },
    amountIn: 53,
    amountOut: 85,
    timestamp: '10/13/2023',
    desc: 'Baby',
  },
  {
    from: { name: 'Cart', bank: 'Tempsoft' },
    to: { name: 'Ivashintsov', bank: 'Biodex' },
    amountIn: 60,
    amountOut: 84,
    timestamp: '8/23/2023',
    desc: 'Industrial',
  },
  {
    from: { name: 'Claudian', bank: 'Zamit' },
    to: { name: 'Ferrige', bank: 'Lotlux' },
    amountIn: 60,
    amountOut: 7,
    timestamp: '6/6/2023',
    desc: 'Sports',
  },
  {
    from: { name: 'Tedman', bank: 'Flexidy' },
    to: { name: 'Jonin', bank: 'Alpha' },
    amountIn: 83,
    amountOut: 81,
    timestamp: '1/6/2023',
    desc: 'Grocery',
  },
  {
    from: { name: 'Darby', bank: 'Bitwolf' },
    to: { name: 'Patrick', bank: 'Ventosanzap' },
    amountIn: 71,
    amountOut: 67,
    timestamp: '1/3/2023',
    desc: 'Electronics',
  },
  {
    from: { name: 'Aurora', bank: 'Solarbreeze' },
    to: { name: 'Waldera', bank: 'Veribet' },
    amountIn: 86,
    amountOut: 78,
    timestamp: '9/30/2023',
    desc: 'Jewelry',
  },
  {
    from: { name: 'Elisha', bank: 'Otcom' },
    to: { name: 'Kitchener', bank: 'Fixflex' },
    amountIn: 36,
    amountOut: 45,
    timestamp: '3/8/2023',
    desc: 'Computers',
  },
  {
    from: { name: 'Barbi', bank: 'Span' },
    to: { name: 'Frantz', bank: 'Hatity' },
    amountIn: 92,
    amountOut: 40,
    timestamp: '7/3/2023',
    desc: 'Beauty',
  },
  {
    from: { name: 'Lucie', bank: 'Pannier' },
    to: { name: 'Schroter', bank: 'Konklab' },
    amountIn: 92,
    amountOut: 2,
    timestamp: '9/15/2023',
    desc: 'Beauty',
  },
  {
    from: { name: 'Erin', bank: 'Fix San' },
    to: { name: 'Carder', bank: 'Latlux' },
    amountIn: 21,
    amountOut: 42,
    timestamp: '7/10/2023',
    desc: 'Garden',
  },
  {
    from: { name: 'Kelcy', bank: 'Daltfresh' },
    to: { name: 'Piper', bank: 'Greenlam' },
    amountIn: 83,
    amountOut: 25,
    timestamp: '7/17/2023',
    desc: 'Automotive',
  },
  {
    from: { name: 'Lucilia', bank: 'Voyatouch' },
    to: { name: 'Shafto', bank: 'Voltsillam' },
    amountIn: 21,
    amountOut: 19,
    timestamp: '11/10/2023',
    desc: 'Clothing',
  },
  {
    from: { name: 'Trude', bank: 'Tresom' },
    to: { name: 'Duggon', bank: 'Y-find' },
    amountIn: 47,
    amountOut: 96,
    timestamp: '6/16/2023',
    desc: 'Grocery',
  },
  {
    from: { name: 'Jessie', bank: 'Stronghold' },
    to: { name: 'Swinford', bank: 'Bitwolf' },
    amountIn: 78,
    amountOut: 72,
    timestamp: '1/12/2023',
    desc: 'Computers',
  },
  {
    from: { name: 'Roobbie', bank: 'Stim' },
    to: { name: 'Boldero', bank: 'Gembucket' },
    amountIn: 3,
    amountOut: 50,
    timestamp: '2/26/2023',
    desc: 'Industrial',
  },
  {
    from: { name: 'Appolonia', bank: 'Cardify' },
    to: { name: 'Birkbeck', bank: 'Alphazap' },
    amountIn: 27,
    amountOut: 57,
    timestamp: '5/15/2023',
    desc: 'Music',
  },
];
